# -*- coding: utf-8 -*-
"""Functions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T8g9B-4TWxJlOqDUjAyAT0m6BUZi1-Hz
"""

def wish(name):
  '''This fuction will greet people'''
  print('good morning',name)
wish('vikas')
wish.__doc__

# function to add number
def add(a,b):
  c=a+b
  return c
  #print('the sum of two numbers is ',c)
add(30,40)

add(40,5)

list1=[1,2,3,4]
list2=list([1,2,3,4])
print(list1)

str1='python programming'
def clean_text(text):
  clean_text=text.strip().lower()
  return clean_text

clean_text(str1)

def odd_or_even(n):
  '''this will print if number is even or odd'''
  if n%2==0:
    print('{} is even number'.format(n))
  else:
    print('{} is odd number'.format(n))

odd_or_even(0)

def function(n):
  for i in range(n):
    print(i)
    if i==2:
      break

function(5)

def grade_students(marks):
  sum_marks=sum(marks)
  avg_marks=sum_marks/len(marks)

  if avg_marks>=90:
    print('Grade A')
  elif avg_marks>=80 and avg_marks<90:
    print('Grade B')
  elif avg_marks>=70 and avg_marks<50:
    print('Grade c')
  else:
    print('Grade F')

grade_students([89,90,91,30])